/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import static javaapplication1.ViewAccessCodes.BindList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rasikh
 */
public class ViewUsers extends javax.swing.JFrame {
private String user;
private String fname;
private String sname;
private String mob;
private String add;
int pos = 0;
    /**
     * Creates new form ViewUsers
     */
    public ViewUsers() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        ShowPosInfo(pos);
    }
    
    public ViewUsers(String user, String fname, String sname, String mob, String add) {
        this.user = user;
        this.fname = fname;
        this.sname = sname;
        this.mob = mob;
        this.add = add;
    }

    public String getuser() {
        return user;
    }
    
    public String getfname() {
        return fname;
    }
    
    public String getsname() {
        return sname;
    }
    
    public String getmob() {
        return mob;
    }
    
    public String getadd() {
        return add;
    }
    
    public static List<ViewUsers> BindList() {
        try {
            SetConnection conn = new SetConnection();
            Connection connect = SetConnection.conn;
            Statement stm = connect.createStatement();
            
            String sql = "select * from user";
            
            ResultSet rs = stm.executeQuery(sql);
            List<ViewUsers> list = new ArrayList<ViewUsers>();
            while(rs.next()) {
                ViewUsers v = new ViewUsers(rs.getString("username"),
                                            rs.getString("fname"),
                                            rs.getString("sname"),
                                            rs.getString("mobile"),
                                            rs.getString("address")
                 );
                list.add(v);
            }
            connect.close();
            return list;
        }
        catch (Exception e) {}
        return null;
    }
    
    public void ShowPosInfo(int index){
        usertxt.setText(BindList().get(index).getuser());
        fnametxt.setText(BindList().get(index).getfname());
        snametxt.setText(BindList().get(index).getsname());
        mobtxt.setText(BindList().get(index).getmob());
        addtxt.setText(BindList().get(index).getadd());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        next = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        snametxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mobtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addtxt = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        UserProfile = new javax.swing.JLabel();
        SecuritySettings = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        CreateAccessCode = new javax.swing.JLabel();
        ViewAccessCodes = new javax.swing.JLabel();
        ViewUsers = new javax.swing.JLabel();
        DeleteUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(null);

        next.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        next.setForeground(new java.awt.Color(236, 240, 241));
        next.setText(" Next");
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        jPanel2.add(next);
        next.setBounds(300, 470, 60, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/rasikh/Downloads/icons8-chevron_right.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(350, 460, 20, 40);

        back.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(236, 240, 241));
        back.setIcon(new javax.swing.ImageIcon("/Users/rasikh/Downloads/icons8-chevron_left.png")); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(200, 460, 80, 40);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText(" Username:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(220, 10, 130, 30);

        usertxt.setEditable(false);
        usertxt.setBackground(new java.awt.Color(108, 122, 137));
        usertxt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        usertxt.setForeground(new java.awt.Color(228, 241, 254));
        usertxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        jPanel2.add(usertxt);
        usertxt.setBounds(180, 40, 210, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("First Name:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(220, 80, 130, 30);

        fnametxt.setEditable(false);
        fnametxt.setBackground(new java.awt.Color(108, 122, 137));
        fnametxt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        fnametxt.setForeground(new java.awt.Color(228, 241, 254));
        fnametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });
        jPanel2.add(fnametxt);
        fnametxt.setBounds(180, 110, 210, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Surname:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(240, 160, 130, 30);

        snametxt.setEditable(false);
        snametxt.setBackground(new java.awt.Color(108, 122, 137));
        snametxt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        snametxt.setForeground(new java.awt.Color(228, 241, 254));
        snametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        snametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snametxtActionPerformed(evt);
            }
        });
        jPanel2.add(snametxt);
        snametxt.setBounds(180, 190, 210, 30);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Mobile:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(260, 240, 64, 30);

        mobtxt.setEditable(false);
        mobtxt.setBackground(new java.awt.Color(108, 122, 137));
        mobtxt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        mobtxt.setForeground(new java.awt.Color(228, 241, 254));
        mobtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mobtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobtxtActionPerformed(evt);
            }
        });
        jPanel2.add(mobtxt);
        mobtxt.setBounds(180, 270, 210, 30);

        addtxt.setEditable(false);
        addtxt.setBackground(new java.awt.Color(108, 122, 137));
        addtxt.setColumns(20);
        addtxt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        addtxt.setForeground(new java.awt.Color(228, 241, 254));
        addtxt.setRows(5);
        jScrollPane1.setViewportView(addtxt);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(160, 350, 270, 100);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Address:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(250, 310, 130, 30);

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));

        UserProfile.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        UserProfile.setForeground(new java.awt.Color(236, 240, 241));
        UserProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-user.png"))); // NOI18N
        UserProfile.setText("User Profile");
        UserProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserProfile.setMinimumSize(new java.awt.Dimension(196, 48));
        UserProfile.setPreferredSize(new java.awt.Dimension(196, 48));
        UserProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UserProfileMouseMoved(evt);
            }
        });
        UserProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserProfileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserProfileMouseExited(evt);
            }
        });

        SecuritySettings.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        SecuritySettings.setForeground(new java.awt.Color(236, 240, 241));
        SecuritySettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-key.png"))); // NOI18N
        SecuritySettings.setText("Security Settings");
        SecuritySettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SecuritySettings.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SecuritySettingsMouseMoved(evt);
            }
        });
        SecuritySettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SecuritySettingsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SecuritySettingsMouseExited(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(236, 240, 241));
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-shutdown.png"))); // NOI18N
        LogOut.setText("Log Out");
        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogOutMouseMoved(evt);
            }
        });
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutMouseExited(evt);
            }
        });

        Home.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(236, 240, 241));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home.png"))); // NOI18N
        Home.setText("Home");
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeMouseMoved(evt);
            }
        });
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });

        CreateAccessCode.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        CreateAccessCode.setForeground(new java.awt.Color(236, 240, 241));
        CreateAccessCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-enter_pin.png"))); // NOI18N
        CreateAccessCode.setText("Create Access Code");
        CreateAccessCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateAccessCode.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CreateAccessCodeMouseMoved(evt);
            }
        });
        CreateAccessCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateAccessCodeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateAccessCodeMouseExited(evt);
            }
        });

        ViewAccessCodes.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ViewAccessCodes.setForeground(new java.awt.Color(236, 240, 241));
        ViewAccessCodes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-visible.png"))); // NOI18N
        ViewAccessCodes.setText("View Access Codes");
        ViewAccessCodes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAccessCodes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewAccessCodesMouseMoved(evt);
            }
        });
        ViewAccessCodes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAccessCodesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewAccessCodesMouseExited(evt);
            }
        });

        ViewUsers.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ViewUsers.setForeground(new java.awt.Color(236, 240, 241));
        ViewUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-conference.png"))); // NOI18N
        ViewUsers.setText("View Users");
        ViewUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewUsers.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewUsersMouseMoved(evt);
            }
        });
        ViewUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewUsersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewUsersMouseExited(evt);
            }
        });

        DeleteUser.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        DeleteUser.setForeground(new java.awt.Color(236, 240, 241));
        DeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-remove_user_male.png"))); // NOI18N
        DeleteUser.setText("Delete User");
        DeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DeleteUserMouseMoved(evt);
            }
        });
        DeleteUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SecuritySettings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addComponent(LogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CreateAccessCode, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addComponent(ViewAccessCodes, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addComponent(ViewUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addComponent(DeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SecuritySettings)
                .addGap(18, 18, 18)
                .addComponent(CreateAccessCode)
                .addGap(18, 18, 18)
                .addComponent(ViewAccessCodes)
                .addGap(18, 18, 18)
                .addComponent(ViewUsers)
                .addGap(18, 18, 18)
                .addComponent(DeleteUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Home)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Dashboard");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 180, 22);

        jLabelClose.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseMoved(evt);
            }
        });
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(810, 10, 12, 22);

        jLabelMin.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(790, 10, 11, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserProfileMouseMoved
        UserProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108,122,137)));
    }//GEN-LAST:event_UserProfileMouseMoved

    private void UserProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserProfileMouseClicked
        AdminDashboard dash = new AdminDashboard();
        dash.setVisible(true);
        dash.pack();
        dash.setLocationRelativeTo(null);
        dash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_UserProfileMouseClicked

    private void UserProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserProfileMouseExited
        UserProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52,73,94)));
    }//GEN-LAST:event_UserProfileMouseExited

    private void SecuritySettingsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecuritySettingsMouseMoved
        SecuritySettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108,122,137)));
    }//GEN-LAST:event_SecuritySettingsMouseMoved

    private void SecuritySettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecuritySettingsMouseClicked
        AdminSecurity sec = new AdminSecurity();
        sec.setVisible(true);
        sec.pack();
        sec.setLocationRelativeTo(null);
        sec.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_SecuritySettingsMouseClicked

    private void SecuritySettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecuritySettingsMouseExited
        SecuritySettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52,73,94)));
    }//GEN-LAST:event_SecuritySettingsMouseExited

    private void LogOutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseMoved
        LogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108,122,137)));
    }//GEN-LAST:event_LogOutMouseMoved

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        Login log = new Login();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LogOutMouseClicked

    private void LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseExited
        LogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52,73,94)));
    }//GEN-LAST:event_LogOutMouseExited

    private void HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseMoved
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108,122,137)));
    }//GEN-LAST:event_HomeMouseMoved

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Admin main = new Admin();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52,73,94)));
    }//GEN-LAST:event_HomeMouseExited

    private void CreateAccessCodeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccessCodeMouseMoved
        CreateAccessCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108,122,137)));
    }//GEN-LAST:event_CreateAccessCodeMouseMoved
    public void addaccesscode(int code) {
            try {
            
            SetConnection conn = new SetConnection();
            Connection connect = SetConnection.conn;
            Statement stm = connect.createStatement();
            
            String sql = "insert into access (code) VALUES ('"+code+"')";
            
            stm.executeUpdate(sql);
            
            connect.close();
        }
        catch (Exception e) {}
        }
    
    public boolean searchaccesscode(int acode) {
        try {
            SetConnection conn = new SetConnection();
            Connection connect = SetConnection.conn;
            Statement stm = connect.createStatement();
            
            String sql = "select * from access where code='"+acode+"'";
            
            ResultSet rs = stm.executeQuery(sql);
            if(rs.next()) {
                return true;
            }
            connect.close();
        }
        catch (Exception e) {}
        return false;
    }
    private void CreateAccessCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccessCodeMouseClicked
       RandNum rand = new RandNum();
                while(searchaccesscode(rand.getRand())) {
                    rand = new RandNum();
                    JOptionPane.showMessageDialog(null, "Your new access code is: "+rand.getRand()+"");
                    addaccesscode(rand.getRand());
                }
                if(!searchaccesscode(rand.getRand())) {
                    JOptionPane.showMessageDialog(null, "Your new access code is: "+rand.getRand()+"");
                    addaccesscode(rand.getRand());
                }
    }//GEN-LAST:event_CreateAccessCodeMouseClicked

    private void CreateAccessCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccessCodeMouseExited
        CreateAccessCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52,73,94)));
    }//GEN-LAST:event_CreateAccessCodeMouseExited

    private void ViewAccessCodesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAccessCodesMouseMoved
        ViewAccessCodes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108,122,137)));
    }//GEN-LAST:event_ViewAccessCodesMouseMoved

    private void ViewAccessCodesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAccessCodesMouseClicked
        ViewAccessCodes view = new ViewAccessCodes();
        view.setVisible(true);
        view.pack();
        view.setLocationRelativeTo(null);
        view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ViewAccessCodesMouseClicked

    private void ViewAccessCodesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAccessCodesMouseExited
        ViewAccessCodes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52,73,94)));
    }//GEN-LAST:event_ViewAccessCodesMouseExited

    private void ViewUsersMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewUsersMouseMoved
        ViewUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108,122,137)));
    }//GEN-LAST:event_ViewUsersMouseMoved

    private void ViewUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewUsersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewUsersMouseClicked

    private void ViewUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewUsersMouseExited
        ViewUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52,73,94)));
    }//GEN-LAST:event_ViewUsersMouseExited

    private void DeleteUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteUserMouseMoved
        DeleteUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108,122,137)));
    }//GEN-LAST:event_DeleteUserMouseMoved

    public boolean deleteuser(String user) {
        try {
            SetConnection conn = new SetConnection();
            Connection connect = SetConnection.conn;
            Statement stm = connect.createStatement();
            
            String sql = "delete from user where username='"+user+"'";
            
            int res = stm.executeUpdate(sql);
            if(res == 1) {
                return true;
            }
            connect.close();
        }
        catch (Exception e) {}
        return false;
    }
    
    public boolean finduser(String user) {
        try {
            SetConnection conn = new SetConnection();
            Connection connect = SetConnection.conn;
            Statement stm = connect.createStatement();
            
            String sql = "select * from user where username='"+user+"'";
            
            ResultSet rs = stm.executeQuery(sql);
            if(rs.next()) {
                return true;
            }
            connect.close();
        }
        catch (Exception e) {}
        return false;
    }
    public void deletetwofactor(String user) {
        try {
            SetConnection conn = new SetConnection();
            Connection connect = SetConnection.conn;
            Statement stm = connect.createStatement();
            
            String sql = "delete from twofactor where user='"+user+"'";
            
            int res = stm.executeUpdate(sql);
            connect.close();
        }
        catch (Exception e) {}
    }
    public void deleteaccesscode(String user) {
        try {
            SetConnection conn = new SetConnection();
            Connection connect = SetConnection.conn;
            Statement stm = connect.createStatement();
            
            String sql = "delete from access where user='"+user+"'";
            
            int res = stm.executeUpdate(sql);
            connect.close();
        }
        catch (Exception e) {}
    }
    
    private void DeleteUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteUserMouseClicked
        int input=1000;
        String deluser = JOptionPane.showInputDialog("Please enter username: ");
        if(finduser(deluser)) {
            input = JOptionPane.showOptionDialog(null, "Do you really want to delete this user?", "Message", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        else {
            JOptionPane.showMessageDialog(null, "No such user exist!");
        }
        if(input == JOptionPane.OK_OPTION)
            {   
                if(deluser.equalsIgnoreCase("admin")) {
                    JOptionPane.showMessageDialog(null, "You can not delete super user!");
                }
                else {
                    if(deleteuser(deluser)) {
                        deletetwofactor(deluser);
                        deleteaccesscode(deluser);
                        JOptionPane.showMessageDialog(null, deluser + " successfully deleted!");
                    }
                }     
        }
        else if(input == JOptionPane.CANCEL_OPTION) {
            //do nothing
        }
    }//GEN-LAST:event_DeleteUserMouseClicked

    private void DeleteUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteUserMouseExited
        DeleteUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52,73,94)));
    }//GEN-LAST:event_DeleteUserMouseExited

    private void jLabelCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseMoved

    }//GEN-LAST:event_jLabelCloseMouseMoved

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited

    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void snametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snametxtActionPerformed

    private void mobtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobtxtActionPerformed

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        pos++;
               if(pos < BindList().size()){
                   ShowPosInfo(pos);
               }
               else{
                   pos = BindList().size() - 1;
                   ShowPosInfo(pos);
                   JOptionPane.showMessageDialog(null, "End of record!");
               }
    }//GEN-LAST:event_nextMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        pos--;
            if(pos > 0){
                ShowPosInfo(pos);                
            }
            else{
                pos = 0;
                ShowPosInfo(pos);
            }
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateAccessCode;
    private javax.swing.JLabel DeleteUser;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel SecuritySettings;
    private javax.swing.JLabel UserProfile;
    private javax.swing.JLabel ViewAccessCodes;
    private javax.swing.JLabel ViewUsers;
    private javax.swing.JTextArea addtxt;
    private javax.swing.JLabel back;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobtxt;
    private javax.swing.JLabel next;
    private javax.swing.JTextField snametxt;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
